# Generated by Django 5.0.6 on 2024-05-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnic_card', models.IntegerField()),
                ('states', models.CharField(auto_created=None, choices=[('Bwp', 'bwp'), ('Isl', 'Islamabad')], max_length=100)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('p_images', models.ImageField(blank=True, upload_to='p_images')),
            ],
        ),
    ]
